### ISSUE TITLE
Criar o Vídeo da Home

### ISSUE THREAD

**Issue by mateuscgc** [InfoJrUFBA/SEMCOMP-2015#25]

**Comment by mateuscgc** [comment]
@leocostaba Leo, é Bom botar cortes de mais de uma palestra no vídeo

**Comment by leocostaba** [comment]
Tudo bem, o problema é só baixar os vídeos de mais de uma hora nessa internet tartaruga

**Comment by mateuscgc** [comment]
@leocostaba Parece que não aparece o vídeo no celular porque o autoplay não funciona, mas ele ainda deve carregar, além disso é preciso ter dois formatos, o **mp4** que já tem e o **Webm**
